version: "3.2"

services:
  node-setup:
    image: alignedlayerd_i
    build:
      context: ../../
      dockerfile: ./Dockerfile
    volumes:
      - ../../prod-sim/${NODE_NAME}:/root/.alignedlayer
      - ../scripts/node.entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh ${NODE_NAME}

  validator-setup:
    image: alignedlayerd_i
    build:
      context: ../../
      dockerfile: ./Dockerfile
    volumes:
      - ../../prod-sim/${NODE_NAME}:/root/.alignedlayer
      - ../scripts/validator.entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh ${NODE_NAME} 1050000stake
    depends_on:
      node-setup:
        condition: service_completed_successfully

  validator-runner:
    image: alignedlayerd_i
    build:
      context: ../../
      dockerfile: ./Dockerfile
    volumes:
      - ../../prod-sim/${NODE_NAME}:/root/.alignedlayer
    command: start
    depends_on:
      validator-setup:
        condition: service_completed_successfully
